### ISSUE TITLE
Syncing players starts having issues after a while

### ISSUE THREAD

**Issue by skippadille** [magdesign/PocketVJ-CP-v3#55]
Hi,

I've been running syncing players for 5 weeks without any issues and syncing nicely. Now they started to have issues with them. Videos started to have random decoding artefacts in them and some of the players stops randomly. The same issues are now happening in two different installations, a three player sync through a switch and the other is just two players connected straight to each other.
Is there some cache or some other temporary memory that gets filled up and needs clearing, or what could cause the issues? The issues stay after rebooting. Running pi3's with official power adapters.

**Comment by magdesign** [comment]
Wow, I never heard of such an issue, strange.
Can you please click in ControlPanel to "Diskspace" and write down the amount of free space.
Then hit the "STOP" button and check again the "Diskspace". Did something change?
With the "STOP" command we clear all .log files in /var/www/

I am not aware of this, just checking with strace  if I can find out something more, hope I can figure it out soon.

You could also try it with "sudo apt-get clean", if you have no idea what I am talking, just "STOP" everything and click "Update All" in the ControlPanel.

**Comment by skippadille** [comment]
The size/space didn't seem to change, 15gb total, 5,8gb/43% available.
I can try the apt-get clean tomorrow morning (they're running at the moment, but with some artefacts).
The videos bit rate is ~14,1mb/s, but they're been running fine for quite long.

**Comment by magdesign** [comment]
I just released an update and added following commands to the " Factory Reset"  Button:

```
sudo rm -rf /tmp/*
sudo rm -rf /var/log/*
sudo rm -rf /var/tmp/*
sudo apt-get clean

```
This should clean up all logs and temp files.
Would be interesting to hear if the artefacts are gone after freeing up some space and also if they return after a few weeks. So I can figure out a permanent fix for this.

**Comment by skippadille** [comment]
I ended up making new sd-cards from a backup img. They're now running fine.
Tried those commands to clean temp files on one of the old cards, and now I can't access CP anymore.
Accessing command line by putting :4200 to address bar works. Player starts as master with auto-play, but with artefacts.

**Comment by magdesign** [comment]
Really weird.
You say after you recovered the images, the player works again but movies still play with artefacts?
If you check the output resolution (Show resolution button), is it 1920x1080 or 1920 x1200, because the later one can cause such issues. Solution would be to force PVJ to play in 1920x1080 under Display settings.
Can you please upload me somewhere the video file so I can test it here (send link to info_at_magdesign.ch)

**Comment by skippadille** [comment]
There's no artefacts in the recovered images, they're running fine at the moment.
Videos are 1920x1080. I still have the old cards with the issues, so i'll try to troubleshoot with them.
It might be something I've done wrong when originally build these...

**Comment by skippadille** [comment]
So clearing /var/log/* seems to kill lighttpd. It needs the log file to run properly. Re-installing got it working again. The artefacts builds up in the video files themselves?! I checked one of the files that had the artefacts after been played for those five weeks, and the video has the same artefacts when played with qt-player on my laptop. When I upload the same exact video (even the Media-Info shows no difference in the files) that it originally was, it has no artefacts in it. So something happens to the video files over time.

**Comment by magdesign** [comment]
Ok, never heard of such an issue.
Are you using an ordered PocketVJ or did you built it by yourself?

**Comment by skippadille** [comment]
I've build these myself

**Comment by magdesign** [comment]
I think then its an issue with fstab settings.

**Comment by skippadille** [comment]
Sounds possible. What would be the correct settings and values for fstab? At the moment it doesn't have tmpfs at all.

**Comment by magdesign** [comment]
try it with "noatime"
